# Generated by Django 5.1.3 on 2024-11-16 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_users_created_at_users_updated_at_alter_users_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyBills',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('consumo', models.FloatField()),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('cpf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
