# Generated by Django 5.1.3 on 2024-11-16 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='energybills',
            table='energy_bills',
        ),
    ]
