# Generated by Django 5.1.3 on 2024-11-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_bills', '0002_alter_energybills_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energybills',
            old_name='consumo',
            new_name='consumption',
        ),
        migrations.RenameField(
            model_name='energybills',
            old_name='valor',
            new_name='value',
        ),
    ]
