# Generated by Django 5.1.3 on 2024-11-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_bills', '0003_rename_consumo_energybills_consumption_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energybills',
            old_name='cpf',
            new_name='usr',
        ),
    ]
