# Generated by Django 5.1.3 on 2024-11-20 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_bills', '0004_rename_cpf_energybills_usr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='energybills',
            old_name='usr',
            new_name='user',
        ),
    ]
