# Generated by Django 5.1.3 on 2024-11-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('energy_bills', '0005_rename_usr_energybills_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energybills',
            name='user',
        ),
    ]
